---
- name: Assignment Playbook
  hosts: web
  tasks:
  - name: Install httpd
    ansible.builtin.dnf:
      name: httpd
      state: latest 

  - name: Create index.html file
    ansible.builtin.copy:
      content: "Welcome to Ansible Bootcamp!"
      dest: /var/www/html/index.html

  - name: Enable and start httpd service
    ansible.builtin.systemd:
      name: httpd
      state: started
      enabled: true

  - name: Allow http in firewalld 
    ansible.posix.firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled
